### ISSUE TITLE
Add additional files used in workflow

### ISSUE THREAD

**Issue by amsnyder** [hytest-org/conus404_ba#6]
You have additional files that are needed by this workflow in your home directory...we should move those to the hytest directory or this repo. Just adding an issue to make sure we don't forget to do this.

**Comment by pnorton-usgs** [comment]
The additional files used by the daily and hourly workflows have been place at:
`/caldera/hovenweep/projects/usgs/water/impd/hytest/working/src_files/conus404-ba_daily`
`/caldera/hovenweep/projects/usgs/water/impd/hytest/working/src_files/conus404-ba_hourly`
